// <auto-generated>
// File này được sinh tự động bởi AudioClipDatabaseEditor.
// KHÔNG sửa tay — mọi thay đổi sẽ bị ghi đè khi nhấn Generate.
// Để thêm ID mới: thêm entry vào AudioClipDatabase.asset rồi nhấn Generate lại.
// </auto-generated>

/// <summary>
/// Toàn bộ Audio ID được sinh tự động từ AudioClipDatabase.
/// Dùng: AudioID.BGM.MainMenu, AudioID.SFX.UIClick, v.v.
/// </summary>
public static class AudioID
{
    public static class BGM
    {
        public const string Music = "bgm_music";
    }

    public static class SFX
    {
        public const string UiClick = "sfx_ui_click";
        public const string UiWin = "sfx_ui_win";
        public const string UiLose = "sfx_ui_lose";
        public const string UiPopup = "sfx_ui_popup";
    }
}
