using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Custom Editor cho AudioClipDatabase.
/// Thêm nút "Generate AudioID" vào Inspector —
/// click sẽ đọc toàn bộ entry trong database rồi sinh lại file AudioID.cs.
///
/// Quy trình làm việc:
///   1. Kéo AudioClip vào AudioClipDatabase.asset trong Inspector, đặt id.
///   2. Click "Generate AudioID" → AudioID.cs được ghi đè.
///   3. Dùng AudioID.SFX.UIClick, AudioID.BGM.MainMenu, v.v. trong code.
/// </summary>
/// Unity Editor sẽ tự động tìm các class có typeof(AudioClipDatabase). 
/// Dù script này không có ref nhưng nó vẫn đang hoạt động.
[CustomEditor(typeof(AudioClipDatabase))]
public class AudioClipDatabaseEditor : Editor
{
    // Đường dẫn file AudioID.cs sẽ được ghi — tính từ thư mục Assets/
    private const string OutputPath = "Assets/_Game/Scripts/04_Audio/AudioID.cs";

    public override void OnInspectorGUI()
    {
        // Vẽ Inspector mặc định
        DrawDefaultInspector();

        EditorGUILayout.Space(8);
        EditorGUILayout.LabelField("Code Generation", EditorStyles.boldLabel);

        // Nút Generate
        GUI.backgroundColor = new Color(0.4f, 0.8f, 0.4f);
        if (GUILayout.Button("Generate AudioID.cs", GUILayout.Height(36)))
        {
            GenerateAudioID((AudioClipDatabase)target);
        }
        GUI.backgroundColor = Color.white;

        EditorGUILayout.HelpBox(
            $"Sinh lại {OutputPath}\ndựa theo danh sách Clips ở trên.",
            MessageType.Info);
    }

    // =========================================================================
    // Generation
    // =========================================================================

    private static void GenerateAudioID(AudioClipDatabase database)
    {
        if (database == null)
        {
            Debug.LogError("[AudioClipDatabaseEditor] database is null.");
            return;
        }

        var clips = database.Clips;
        if (clips == null || clips.Count == 0)
        {
            Debug.LogWarning("[AudioClipDatabaseEditor] Không có entry nào trong database.");
            return;
        }

        // ── Phân loại theo prefix ──────────────────────────────────────────
        // bgm_*  → BGM class
        // sfx_*  → SFX class (không cần phân nhóm nhỏ hơn)
        // còn lại → Other class

        var bgm   = new System.Collections.Generic.List<AudioClipEntry>();
        var sfx   = new System.Collections.Generic.List<AudioClipEntry>();
        var other = new System.Collections.Generic.List<AudioClipEntry>();

        foreach (AudioClipEntry entry in clips)
        {
            if (entry == null || string.IsNullOrWhiteSpace(entry.id))
                continue;

            if (entry.id.StartsWith("bgm_", System.StringComparison.OrdinalIgnoreCase))
                bgm.Add(entry);
            else if (entry.id.StartsWith("sfx_", System.StringComparison.OrdinalIgnoreCase))
                sfx.Add(entry);
            else
                other.Add(entry);
        }

        // ── Build source ───────────────────────────────────────────────────
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// File này được sinh tự động bởi AudioClipDatabaseEditor.");
        sb.AppendLine("// KHÔNG sửa tay — mọi thay đổi sẽ bị ghi đè khi nhấn Generate.");
        sb.AppendLine("// Để thêm ID mới: thêm entry vào AudioClipDatabase.asset rồi nhấn Generate lại.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Toàn bộ Audio ID được sinh tự động từ AudioClipDatabase.");
        sb.AppendLine("/// Dùng: AudioID.BGM.MainMenu, AudioID.SFX.UIClick, v.v.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class AudioID");
        sb.AppendLine("{");

        // BGM class
        if (bgm.Count > 0)
        {
            sb.AppendLine("    public static class BGM");
            sb.AppendLine("    {");
            foreach (AudioClipEntry entry in bgm)
            {
                string constName = ToConstName(entry.id);
                sb.AppendLine($"        public const string {constName} = \"{entry.id}\";");
            }
            sb.AppendLine("    }");
        }

        // SFX class
        if (sfx.Count > 0)
        {
            if (bgm.Count > 0) sb.AppendLine();
            sb.AppendLine("    public static class SFX");
            sb.AppendLine("    {");
            foreach (AudioClipEntry entry in sfx)
            {
                string constName = ToConstName(entry.id);
                sb.AppendLine($"        public const string {constName} = \"{entry.id}\";");
            }
            sb.AppendLine("    }");
        }

        // Other class (không có prefix chuẩn)
        if (other.Count > 0)
        {
            if (bgm.Count > 0 || sfx.Count > 0) sb.AppendLine();
            sb.AppendLine("    public static class Other");
            sb.AppendLine("    {");
            foreach (AudioClipEntry entry in other)
            {
                string constName = ToConstName(entry.id);
                sb.AppendLine($"        public const string {constName} = \"{entry.id}\";");
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        // ── Ghi file ──────────────────────────────────────────────────────
        string fullPath = Path.Combine(
            Path.GetDirectoryName(Application.dataPath),
            OutputPath.Replace('/', Path.DirectorySeparatorChar));

        string directory = Path.GetDirectoryName(fullPath);
        if (!Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);

        AssetDatabase.ImportAsset(OutputPath);
        AssetDatabase.Refresh();

        Debug.Log($"[AudioClipDatabaseEditor] AudioID.cs đã được sinh tại: {OutputPath}");
        EditorUtility.DisplayDialog(
            "Generate thành công",
            $"AudioID.cs đã được cập nhật.\n\nBGM: {bgm.Count} IDs\nSFX: {sfx.Count} IDs\nOther: {other.Count} IDs",
            "OK");
    }

    // =========================================================================
    // Helper: "bgm_main_menu" → "MainMenu", "sfx_ui_click" → "UiClick"
    // =========================================================================

    /// <summary>
    /// Chuyển id string thành PascalCase constant name, bỏ prefix bgm_/sfx_.
    ///
    /// Ví dụ:
    ///   bgm_main_menu   → MainMenu
    ///   sfx_ui_click    → UiClick
    ///   sfx_gameover_bomb → GameoverBomb
    /// </summary>
    private static string ToConstName(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
            return "Unknown";

        // Bỏ prefix bgm_ hoặc sfx_
        string stripped = id;
        if (stripped.StartsWith("bgm_", System.StringComparison.OrdinalIgnoreCase))
            stripped = stripped.Substring(4);
        else if (stripped.StartsWith("sfx_", System.StringComparison.OrdinalIgnoreCase))
            stripped = stripped.Substring(4);

        // Split theo _ rồi PascalCase từng phần
        string[] parts = stripped.Split('_');
        var sb = new StringBuilder();
        foreach (string part in parts)
        {
            if (string.IsNullOrWhiteSpace(part)) continue;
            sb.Append(char.ToUpperInvariant(part[0]));
            if (part.Length > 1)
                sb.Append(part.Substring(1).ToLowerInvariant());
        }

        // Đảm bảo không bắt đầu bằng số
        string result = sb.ToString();
        if (result.Length > 0 && char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }
}
